optimisticRepeatInstall: true
strictPeerDependencies: true
dedupePeers: true

overrides:
  "webpack-image-resize-loader>sharp": "^0.33.4"
  "@types/zip-webpack-plugin>@types/webpack": "^5.0.0"

allowBuilds:
  core-js-pure: true
  sharp: true
